# Generated by Django 4.1.4 on 2022-12-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='comment/image'),
        ),
    ]
