# Generated by Django 4.1.2 on 2022-12-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_time',
        ),
    ]
