# Generated by Django 4.1.2 on 2022-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('qus', 'questions'), ('ent', 'entertainment'), ('exp', 'experiences')], default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post', to='post.tag'),
        ),
    ]
