# Generated by Django 4.1.2 on 2022-11-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_status_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='category',
        ),
    ]
