# Generated by Django 4.1.2 on 2022-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_status_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('qus', 'questions'), ('ent', 'entertainment'), ('exp', 'experiences')], default='ent', max_length=3),
        ),
    ]
