# Generated by Django 4.1.4 on 2022-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/preview.jpg', upload_to='post/image'),
        ),
    ]
