# Generated by Django 4.1.4 on 2022-12-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='post/image/default.jpg', upload_to='post/image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('questions', 'questions'), ('entertainment', 'entertainment'), ('experiences', 'experiences')], default='entertainment', max_length=20),
        ),
    ]
