# Generated by Django 4.1.4 on 2022-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_image_post_cover_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment/image'),
        ),
    ]
