# Generated by Django 4.1.4 on 2022-12-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
