# Generated by Django 4.1.2 on 2022-10-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post_tag_alter_comments_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post', to='user.tag'),
        ),
    ]
