# Generated by Django 4.1.2 on 2022-11-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='<anon>', max_length=256),
        ),
    ]
