# Generated by Django 4.1.2 on 2022-11-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userimage_postimage_commentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CommentImage',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
